Add bookings
kmmins/java-shareit pull request #2
Opened 2023-04-28 00:12 UTC by kmmins

Здравствуйте, посмотрите, пожалуйста, работу.

2023-04-30 14:54 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
Не понравилось что вы вместо одного репозитория, например, 
public interface SomeRepo extends JpaRepository<Object, Long> создаете 3 класса.

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryDbImpl.java
> +public class BookingRepositoryDbImpl implements BookingRepository {
это по мне лишний класс, BookingRepositoryJpa достаточно

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository {
это по мне лишний класс, BookingRepositoryJpa достаточно

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingEntity dB = bookingRepository.getById(bookingId);
плохое название для переменной, можно booking

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<BookingEntity> allFound = bookingRepository.getAllForUser(userId);
плохое название для переменной, можно bookings

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        createdModel.setOwnerId((userId));
вместо этих сеттеров вы же можете юзать маппер

2023-04-30 14:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        BookingEntity xBooking = null;
плохое название для переменной

2023-05-01 11:04 UTC, kmmins commented
Все поправил, посмотрите.

2023-05-01 13:25 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-01 13:59 UTC, merged