Add item requests
kmmins/java-shareit pull request #3
Opened 2023-05-07 11:34 UTC by kmmins

Здравствуйте, посмотрите, пожалуйста, работу.

2023-05-14 07:49 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingExceptionHandler.java
>      @ResponseStatus(HttpStatus.BAD_REQUEST)
давайте лучше сделаем один handler и будем держать его в пакете handler на уровне с booking/item/user

2023-05-14 07:51 UTC, ErkinKasymaliev requested changes
привет, оставил коммент

2023-05-15 09:12 UTC, kmmins commented
Объединил в одни.

2023-05-15 10:53 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-15 11:37 UTC, merged